# Streamlit secrets configuration for Remiro AI
# Your Google Gemini API key

GOOGLE_API_KEY = "AIzaSyA-S6VAHGMwQ4uNqBriZvBV2l7gROj1rr0"

# To get your Google API key:
# 1. Go to https://ai.google.dev/
# 2. Create a new API key for Gemini API
# 3. Replace the placeholder above with your actual key
# 4. Make sure to keep this file secure and never commit it to version control